### PR TITLE
Increase Max Sample/S & FFT Len, Minor UI Changes

### PR DESCRIPTION
**Pull request by nfsmaster208**
Added support for 192kHz devices, doubled maximum FFT length choice, and
fixed support for landscape view musical note (pitch) view.

Known Issue: At maximum FFT length and Sample Rate settings, linear view
experiences a bug and does not display correctly.

Workaround: Please choose either logarithmic or note view at this high
(maximum) performance level.

Other changes:

**Simplify Portrait Graph Context to 1D/2D**

Provides users in portrait mode a simplified context for which to choose
between the spectrogram (2D) graph view and the spectrum (1D) graph
view. Landscape has more screen "real estate" to display the "spam" and
"spum" titles, which will show while switching between display
orientations.

**Add in support for landscape note view.**

Now it is possible to choose to access the Pitch view in landscape.

**Make animation delay more responsive feeling.**

Very minor change but helps the app feel slightly more responsive.

Note: The "refresh" branch is a pulled directly from the latest version of bewantbe/master and has only the real changes from PR #9, but in a much cleaner style.

### CODE REVIEW

**Comment by bewantbe** [comment]
The "Known Issue" is actually the reason why I didn't add higher FFT length... There is a limitation on the dimension of bitmap when drawing screen, so one has to either split the bitmap or re-sample to a smaller size (like what log-scale do).

**Comment by bewantbe** [comment]
Merged (tentatively).

But the network graph in [my view](https://github.com/bewantbe/audio-analyzer-for-android/network) looks odd, it didn't count that commit (63f7c39) in your column. And in [your view](https://github.com/nfsmaster208/audio-analyzer-for-android/network) it is odd also.

Another potential problem is when you initiate a new pull request based on your master branch, the redundancy (adding and removing the FilePicker) will be reintroduced.

My suggestion in PR https://github.com/bewantbe/audio-analyzer-for-android/pull/9 means the following commands (assume you are using Linux; if windows, might need some minor changes):

(on your side)

    $ git clone YOUR-REPOSITORY
    $ cd YOUR-REPOSITORY
    $ git checkout master
    $ git filter-branch --force --index-filter \
      'git rm -r --cached --ignore-unmatch FilePickerLibrary/' \
      --prune-empty --tag-name-filter cat -- --all
    $ git push origin --force --all

It is still not too late to do that. 

For me, merge multiple commits is OK, my concern is only about the "FilePicker" which the size is larger than this app itself.

After you done this "filter-branch", I can then cancel this merge, and merge your (yet another) PR.

Feel free to contact me or discuss here if you have any question.

**Comment by DSteve595** [comment]
@bewantbe: Hmm, I'm not seeing what's strange about the network view. It looks like this PR (not #9) contained only one commit with minimal changes. Were you maybe looking at his master branch? This PR is based off of a different branch of his.

**Comment by bewantbe** [comment]
I am confused, so @nfsmaster208 edited on branch bewantbe/master and then make a PR?

From here https://github.com/nfsmaster208/audio-analyzer-for-android/network, I'm not involved until this last merge, that's normal?

**Comment by DSteve595** [comment]
Yes, he reset to your latest commit on bewantbe/master and branched off of there.

**Comment by bewantbe** [comment]
OK... then keep this merge.

**Pull request merged**
